# Generated by Django 5.2 on 2025-08-18 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kyc',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='kyc',
            name='status',
            field=models.CharField(choices=[('init', 'Init'), ('pending', 'Pending'), ('queued', 'Queued'), ('onHold', 'On Hold'), ('prechecked', 'Prechecked'), ('completed', 'Completed'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='KYCResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('sumsub', 'Sumsub'), ('veriff', 'Veriff')], default='sumsub', max_length=32)),
                ('applicant_id', models.CharField(blank=True, max_length=255, null=True)),
                ('inspection_id', models.CharField(blank=True, max_length=255, null=True)),
                ('correlation_id', models.CharField(blank=True, max_length=255, null=True)),
                ('level_name', models.CharField(blank=True, max_length=255, null=True)),
                ('event_type', models.CharField(max_length=255)),
                ('review_status', models.CharField(blank=True, max_length=100, null=True)),
                ('review_answer', models.CharField(blank=True, max_length=100, null=True)),
                ('raw_payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_results', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
