# Generated by Django 5.2 on 2025-08-31 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_kyc_id_alter_kycresult_id_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='api_key',
            field=models.CharField(blank=True, help_text='Kill Bill tenant API key', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='api_secret',
            field=models.CharField(blank=True, help_text='Kill Bill tenant API secret', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='kb_default_account_id',
            field=models.CharField(blank=True, help_text='Default Kill Bill account ID', max_length=64, null=True),
        ),
    ]
