# Generated by Django 5.2 on 2025-08-31 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_api_key_user_api_secret_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kb_tenant_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='api_key',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='api_secret',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='kb_default_account_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
