# Generated by Django 5.2.6 on 2025-09-08 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='router',
            table='router',
        ),
        migrations.AlterModelTable(
            name='transaction',
            table='transaction',
        ),
        migrations.AlterModelTable(
            name='transactionstatus',
            table='transactionstatus',
        ),
        migrations.AlterModelTable(
            name='withdraw',
            table='withdraw',
        ),
    ]
